Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -4,13 +4,21 @@ jobs:
   bug:
     runs-on: ubuntu-latest
     steps:
-      - name: Fail step
-        run: exit 1
+#       - name: Fail step
+#         run: exit 1
 
       - name: Upload artifacts (with if true check)
         if: ${{ 0 == 0 }}
-        run: echo ${{ 0 == 0 }}
+        run: echo "zero equals zero ${{ 0 == 0 }}"
 
+      - name: testing with true
+        if: ${{ true }}
+        run: echo "if true is true"
+
+      - name: test
+        if: $ {{ 0 == 1 }}
+        run: echo "zero equals 1 "
+        
       - name: Upload artifacts (with always)
         if: ${{ always() }}
         run: echo "Would instead use actions/artifacts!"
